services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: honoua
      POSTGRES_USER: honou
      POSTGRES_PASSWORD: Honou2035Lg!
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U honou -d honoua"]
      interval: 5s
      timeout: 5s
      retries: 20
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      PGHOST: postgres
      PGPORT: "5432"
      PGDATABASE: honoua
      PGUSER: honou
      PGPASSWORD: Honou2035Lg!
      # Ou bien, si ton app lit DATABASE_URL :
      # DATABASE_URL: postgresql://honou:honou@postgres:5432/honoua
    ports:
      - "8000:8000"
    command: >
      sh -c "
      PGPASSWORD=honou psql -h postgres -U honou -d honoua -f /app/bootstrap.sql &&
      uvicorn app.main:app --host 0.0.0.0 --port 8000
      "

volumes:
  pgdata:
