"""a41_0001 add user_notification_preferences

Revision ID: e5222ce36723
Revises: a41_merge_heads
Create Date: 2025-11-01 11:54:54.681475

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e5222ce36723'
down_revision = 'a41_merge_heads'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_notification_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('frequency', sa.Enum('immediate', 'hourly', 'daily', 'weekly', name='notification_frequency'), server_default='immediate', nullable=False),
    sa.Column('types', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=True),
    sa.Column('last_notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_notification_preferences_id'), 'user_notification_preferences', ['id'], unique=False)
    op.create_index(op.f('ix_user_notification_preferences_user_id'), 'user_notification_preferences', ['user_id'], unique=False)
# SAFE_DISABLED:     op.drop_table('user_groups')
# SAFE_DISABLED:     op.drop_table('token_blacklist')
# SAFE_DISABLED:     op.drop_index(op.f('ix_emission_factors_cat_unit_valid'), table_name='emission_factors')
# SAFE_DISABLED:     op.drop_table('emission_factors')
# SAFE_DISABLED:     op.drop_index(op.f('idx_lb_month_scope'), table_name='leaderboard_monthly')
# SAFE_DISABLED:     op.drop_table('leaderboard_monthly')
# SAFE_DISABLED:     op.drop_index(op.f('idx_emcalc_category'), table_name='emission_calculations')
# SAFE_DISABLED:     op.drop_index(op.f('idx_emcalc_session_created'), table_name='emission_calculations')
# SAFE_DISABLED:     op.drop_index(op.f('ix_emission_calculations_category'), table_name='emission_calculations')
# SAFE_DISABLED:     op.drop_index(op.f('ix_emission_calculations_product_created'), table_name='emission_calculations')
# SAFE_DISABLED:     op.drop_index(op.f('ix_emission_calculations_session'), table_name='emission_calculations')
# SAFE_DISABLED:     op.drop_table('emission_calculations')
# SAFE_DISABLED:     op.drop_index(op.f('idx_product_brand'), table_name='product')
# SAFE_DISABLED:     op.drop_index(op.f('idx_product_ean'), table_name='product')
# SAFE_DISABLED:     op.drop_index(op.f('idx_product_name'), table_name='product', postgresql_using='gin')
# SAFE_DISABLED:     op.drop_table('product')
# SAFE_DISABLED:     op.drop_table('user_group_sessions')
# SAFE_DISABLED:     op.drop_index(op.f('ix_audit_events_created_at'), table_name='audit_events')
# SAFE_DISABLED:     op.drop_index(op.f('ix_audit_events_event_type'), table_name='audit_events')
# SAFE_DISABLED:     op.drop_table('audit_events')
# SAFE_DISABLED:     op.drop_index(op.f('ix_token_ledger_jti'), table_name='token_ledger')
# SAFE_DISABLED:     op.drop_index(op.f('ix_token_ledger_user_id'), table_name='token_ledger')
# SAFE_DISABLED:     op.drop_table('token_ledger')
# SAFE_DISABLED:     op.drop_index(op.f('idx_ef_category'), table_name='emission_factor')
# SAFE_DISABLED:     op.drop_table('emission_factor')
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emission_factor',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('category', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('subcategory', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('unit', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('value', sa.NUMERIC(precision=12, scale=4), autoincrement=False, nullable=False),
    sa.Column('source', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('emission_factor_pkey'))
    )
    op.create_index(op.f('idx_ef_category'), 'emission_factor', ['category', 'subcategory'], unique=False)
    op.create_table('token_ledger',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('jti', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('issued_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('replaced_by_jti', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('revoked_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('revoked_reason', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('ip', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('token_ledger_pkey')),
    sa.UniqueConstraint('jti', name=op.f('token_ledger_jti_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_token_ledger_user_id'), 'token_ledger', ['user_id'], unique=False)
    op.create_index(op.f('ix_token_ledger_jti'), 'token_ledger', ['jti'], unique=True)
    op.create_table('audit_events',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('event_type', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('message', sa.VARCHAR(length=512), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('audit_events_pkey'))
    )
    op.create_index(op.f('ix_audit_events_event_type'), 'audit_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_audit_events_created_at'), 'audit_events', ['created_at'], unique=False)
    op.create_table('user_group_sessions',
    sa.Column('group_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('added_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['user_groups.id'], name=op.f('user_group_sessions_group_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('group_id', 'session_id', name=op.f('user_group_sessions_pkey'))
    )
    op.create_table('product',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ean', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('brand', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('category', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('image_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('product_pkey')),
    sa.UniqueConstraint('ean', name=op.f('product_ean_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_product_name'), 'product', [sa.literal_column("to_tsvector('simple'::regconfig, name)")], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_product_ean'), 'product', ['ean'], unique=False)
    op.create_index(op.f('idx_product_brand'), 'product', ['brand'], unique=False)
    op.create_table('emission_calculations',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('category_code', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.NUMERIC(precision=18, scale=6), autoincrement=False, nullable=False),
    sa.Column('quantity_unit', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('normalized_qty', sa.NUMERIC(precision=18, scale=6), autoincrement=False, nullable=False),
    sa.Column('factor_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('emissions_gco2e', sa.NUMERIC(precision=18, scale=6), autoincrement=False, nullable=False),
    sa.Column('method', sa.TEXT(), server_default=sa.text("'direct_factor'::text"), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('idempotency_key', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.CheckConstraint("quantity_unit = ANY (ARRAY['g'::text, 'kg'::text, 'ml'::text, 'l'::text, 'piece'::text])", name=op.f('ck_emission_calculations_unit')),
    sa.ForeignKeyConstraint(['factor_id'], ['emission_factors.id'], name=op.f('emission_calculations_factor_id_fkey'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('emission_calculations_pkey')),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_emission_calculations_idem'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_emission_calculations_session'), 'emission_calculations', ['session_id'], unique=False)
    op.create_index(op.f('ix_emission_calculations_product_created'), 'emission_calculations', ['product_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_emission_calculations_category'), 'emission_calculations', ['category_code'], unique=False)
    op.create_index(op.f('idx_emcalc_session_created'), 'emission_calculations', ['session_id', 'created_at'], unique=False)
    op.create_index(op.f('idx_emcalc_category'), 'emission_calculations', ['category_code'], unique=False)
    op.create_table('leaderboard_monthly',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('month', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('scope', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('pseudo', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('score', sa.NUMERIC(precision=12, scale=4), autoincrement=False, nullable=False),
    sa.Column('sessions', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('leaderboard_monthly_pkey'))
    )
    op.create_index(op.f('idx_lb_month_scope'), 'leaderboard_monthly', ['month', 'scope'], unique=False)
    op.create_table('emission_factors',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('category_code', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('unit', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('factor_gco2e_per_unit', sa.NUMERIC(precision=18, scale=6), autoincrement=False, nullable=False),
    sa.Column('source', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('version', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('valid_from', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('valid_to', sa.DATE(), autoincrement=False, nullable=True),
    sa.CheckConstraint("unit = ANY (ARRAY['g'::text, 'kg'::text, 'ml'::text, 'l'::text, 'piece'::text])", name=op.f('ck_emission_factors_unit')),
    sa.PrimaryKeyConstraint('id', name=op.f('emission_factors_pkey'))
    )
    op.create_index(op.f('ix_emission_factors_cat_unit_valid'), 'emission_factors', ['category_code', 'unit', 'valid_from', 'valid_to'], unique=False)
    op.create_table('token_blacklist',
    sa.Column('jti', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('revoked_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('reason', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('jti', name=op.f('token_blacklist_pkey'))
    )
    op.create_table('user_groups',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('owner_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('user_groups_pkey'))
    )
    op.drop_index(op.f('ix_user_notification_preferences_user_id'), table_name='user_notification_preferences')
    op.drop_index(op.f('ix_user_notification_preferences_id'), table_name='user_notification_preferences')
    op.drop_table('user_notification_preferences')
    # ### end Alembic commands ###
